export const LEAGUES = [
  "Champion I",
  "Champion II",
  "Champion III",
  "Master I",
  "Master II",
  "Master III",
  "Crystal I",
  "Crystal II",
  "Crystal III",
  "Gold I",
  "Gold II",
  "Gold III",
  "Silver I",
  "Silver II",
  "Silver III",
  "Bronze I",
  "Bronze II",
  "Bronze III",
];

// Bonos base por liga (según tabla oficial)
export const BASE_BONUSES = {
  "Champion I": 4,
  "Champion II": 4,
  "Champion III": 4,
  "Master I": 3,
  "Master II": 3,
  "Master III": 3,
  "Crystal I": 2,
  "Crystal II": 2,
  "Crystal III": 2,
  "Gold I": 2,
  "Gold II": 2,
  "Gold III": 2,
  "Silver I": 1,
  "Silver II": 1,
  "Silver III": 1,
  "Bronze I": 1,
  "Bronze II": 1,
  "Bronze III": 1,
};

// Medallas por bono según liga
export const MEDAL_VALUES = {
  "Champion I": 105,
  "Champion II": 100,
  "Champion III": 95,
  "Master I": 90,
  "Master II": 85,
  "Master III": 80,
  "Crystal I": 75,
  "Crystal II": 70,
  "Crystal III": 65,
  "Gold I": 60,
  "Gold II": 55,
  "Gold III": 50,
  "Silver I": 45,
  "Silver II": 40,
  "Silver III": 40,
  "Bronze I": 35,
  "Bronze II": 35,
  "Bronze III": 35,
};

export const DEFAULT_VISIBLE_COLS = {
  th: true,
  missAtk: true,
  missDef: false,
  netStars: true,
  netPercent: false,
  threeRate: true,
  starGain: false,
  percentGain: false,
  starGive: false,
  percentGive: false,
};
